# Generated by Django 6.0.5 on 2026-06-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agenttask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='task_type',
            field=models.CharField(choices=[('POLICY_SNAPSHOT_SUMMARY', 'Policy snapshot summary'), ('DOCUMENT_ANALYSIS', 'Document analysis'), ('CASE_ANALYSIS', 'Case analysis')], max_length=80),
        ),
    ]
