# Generated by Django 6.0.5 on 2026-06-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agenttask_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttask',
            name='task_type',
            field=models.CharField(choices=[('POLICY_SNAPSHOT_SUMMARY', 'Policy snapshot summary'), ('DOCUMENT_ANALYSIS', 'Document analysis'), ('CASE_ANALYSIS', 'Case analysis'), ('SUPERVISOR_CASE_REVIEW', 'Supervisor case review'), ('CLIENT_CASE_CHAT', 'Client case chat')], max_length=80),
        ),
    ]
