# Generated by Django 6.0.5 on 2026-06-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agenttask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentresult',
            name='output_schema_version',
            field=models.CharField(default='agent-output.v1', max_length=80),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='agent_protocol_version',
            field=models.CharField(default='agent-runtime.v1', max_length=80),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='context_schema_version',
            field=models.CharField(default='agent-context.v1', max_length=80),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='input_schema_version',
            field=models.CharField(default='agent-input.v1', max_length=80),
        ),
    ]
