# Generated by Django 6.0.5 on 2026-06-14 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agencyworkflowtemplate'),
        ('agents', '0007_clientchatsocketticket'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='agenttask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'RUNNING'), ('content_type__isnull', False), ('object_id__isnull', False), models.Q(('task_type', 'CLIENT_CASE_CHAT'), _negated=True)), fields=('task_type', 'content_type', 'object_id'), name='unique_running_agent_task_per_target'),
        ),
    ]
